Support validation of all RO-Crated in the GitHub Action

diff --git a/.github/workflows/validate-ro-crate.yml b/.github/workflows/validate-ro-crate.yml
--- a/.github/workflows/validate-ro-crate.yml
+++ b/.github/workflows/validate-ro-crate.yml
@@ -1,9 +1,6 @@
-name: Validate RO-Crate
+name: Validate all RO-Crates
 
 on:
-  push:
-    paths:
-      - '**/ro-crate-metadata.json'
   pull_request:
     paths:
       - '**/ro-crate-metadata.json'
@@ -22,8 +19,20 @@ jobs:
         with:
           python-version: '3.10'
 
-      - name: Install rocrate
-        run: pip install rocrate
+      - name: Install roc-validator
+        run:  pip install roc-validator
 
-      - name: Run RO-Crate validation
-        run: rocrate-validator validate -p ro-crate-1.1 ./
+      - name: Validate all RO-Crates in subdirectories
+        run: |
+                for d in */ ; do
+                  if [ -f "$d/ro-crate-metadata.json" ]; then
+                    echo "Validating $d"
+                    rocrate-validator validate -p ro-crate-1.1 --verbose --no-paging "$d"
+                    if [ $? -ne 0 ]; then
+                      echo "Validation failed in $d"
+                      exit 1
+                    fi
+                  else
+                    echo "Skipping $d (no ro-crate-metadata.json found)"
+                  fi
+                done
